name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy in Heroku
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "🚀️ deploy docker container in Heroku"
        uses: akhileshns/heroku-deploy@v3.12.12
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "movies-api-flask"
          heroku_email: "valerii.martell@gmail.com"
          usedocker: true
          remote_branch: main
            
